# Generated by Django 6.0.4 on 2026-05-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Retur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("kode_retur", models.CharField(max_length=50, unique=True)),
                ("tanggal", models.DateField()),
                ("alasan", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROSES", "Diproses"),
                            ("SELESAI", "Selesai"),
                            ("DITOLAK", "Ditolak"),
                        ],
                        default="PROSES",
                        max_length=20,
                    ),
                ),
                (
                    "_total_nilai",
                    models.DecimalField(
                        db_column="total_nilai",
                        decimal_places=2,
                        default=0,
                        help_text="Private. Akses via property `total_nilai`.",
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retur",
                "verbose_name_plural": "Retur",
                "db_table": "penjualan_retur",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("kode_invoice", models.CharField(max_length=50, unique=True)),
                ("tanggal", models.DateField()),
                ("pelanggan_nama", models.CharField(max_length=200)),
                (
                    "metode",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("QRIS", "QRIS"),
                            ("Transfer", "Transfer"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SELESAI", "Selesai"),
                            ("PROSES", "Diproses"),
                            ("BATAL", "Batal"),
                        ],
                        default="SELESAI",
                        max_length=20,
                    ),
                ),
                (
                    "_total",
                    models.DecimalField(
                        db_column="total",
                        decimal_places=2,
                        default=0,
                        help_text="Private. Akses via property `total`.",
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksi",
                "verbose_name_plural": "Transaksi",
                "db_table": "penjualan_transaksi",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReturDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "nilai",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retur_detail_set",
                        to="master.produk",
                    ),
                ),
                (
                    "retur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_set",
                        to="penjualan.retur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retur Detail",
                "verbose_name_plural": "Retur Detail",
                "db_table": "penjualan_retur_detail",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="retur",
            name="transaksi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retur_set",
                to="penjualan.transaksi",
            ),
        ),
        migrations.CreateModel(
            name="TransaksiDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("qty", models.IntegerField(default=1)),
                (
                    "harga_satuan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "produk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaksi_detail_set",
                        to="master.produk",
                    ),
                ),
                (
                    "transaksi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail_set",
                        to="penjualan.transaksi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksi Detail",
                "verbose_name_plural": "Transaksi Detail",
                "db_table": "penjualan_transaksi_detail",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
