# Generated by Django 6.0.4 on 2026-05-27 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("deskripsi", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
                "db_table": "master_kategori",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("nama", models.CharField(max_length=200)),
                ("no_hp", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("alamat", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("Aktif", "Aktif"), ("Nonaktif", "Nonaktif")],
                        default="Aktif",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Supplier",
                "db_table": "master_supplier",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                ("kode_produk", models.CharField(max_length=20, unique=True)),
                ("nama", models.CharField(max_length=200)),
                (
                    "_harga",
                    models.DecimalField(
                        db_column="harga",
                        decimal_places=2,
                        default=0,
                        help_text="Private field. Akses via property `harga`.",
                        max_digits=12,
                    ),
                ),
                ("stok", models.IntegerField(default=0)),
                ("stok_minimum", models.IntegerField(default=5)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produk_set",
                        to="master.kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produk",
                "verbose_name_plural": "Produk",
                "db_table": "master_produk",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierKategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "_is_active",
                    models.BooleanField(
                        db_column="is_active",
                        default=True,
                        help_text="Dikelola via property & soft_delete(), bukan langsung.",
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_set",
                        to="master.kategori",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kategori_set",
                        to="master.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Kategori",
                "verbose_name_plural": "Supplier Kategori",
                "db_table": "master_supplier_kategori",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("supplier", "kategori")},
            },
        ),
    ]
