# Generated by Django 6.0.4 on 2026-05-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="status",
        ),
    ]
