# Generated by Django 6.0.4 on 2026-05-29 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("master", "0002_remove_supplier_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="produk",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produk_set",
                to="master.supplier",
            ),
        ),
    ]
